on:
  push:
    branches: [ '*' ]

jobs:
  run-python-unit-tests:
    name: Run python unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: |
          docker build -t python_measure_test .
          docker run --rm \
            -v ${{ github.workspace }}/test_results:/app/test_results \
            python_measure_test

      - name: Check for FAILURE in pytest_output.txt
        run: |
          ls test_results
          cat test_results/pytest_output.txt
          if grep -q 'FAILURE' test_results/pytest_output.txt; then
            exit 1
          fi

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test_results
          path: test_results/