on:
  push:
    branches: [ '*' ]

jobs:
  run-python-unit-tests:
    name: Run python unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install openstudio
          pip install copper-bem
          pip install constrain

      - name: Find directories containing measure.py
        id: find_python_measure_dirs
        run: |
          python_measure_dirs=$(find . -type f -name 'measure.py' -exec dirname {} \; | uniq | tr '\n' ' ')
          echo "python_measure_dirs=$python_measure_dirs" >> $GITHUB_OUTPUT

      - name: Run OpenStudio measure check
        run: |
          for dir in ${{ steps.find_python_measure_dirs.outputs.python_measure_dirs }}; do
            echo "Running OpenStudio measure check for $dir"
            openstudio measure -t $dir > measure_check_output.txt

            cat measure_check_output.txt
            # grep -v -E "" measure_check_output.txt > filtered_output.txt

            # if grep -q -i "error" filtered_output.txt; then
            #   echo "Unexpected errors found in $dir:"
            #   cat filtered_output.txt
            #   exit 1
            # fi
          done

      - name: Run tests
        run: |
          for dir in ${{ steps.find_python_measure_dirs.outputs.python_measure_dirs }}; do
            pytest $dir
          done